### ISSUE TITLE
Dependent Plugin missing

### ISSUE THREAD

**Issue by AnyTimeTraveler** [rm-code/love-IDEA-plugin#16]
The Lua Plugin this Plugin depends on [lua-for-idea](https://bitbucket.org/sylvanaar2/lua-for-idea/wiki/Home) is no longer available.

Is it still possible to use this plugin and if so, how do you install it?

**Comment by rm-code** [comment]
Sorry for the late reply. Leaving this here for any latecomers arriving:

Looks like [EmmyLua](https://github.com/EmmyLua) and the [Emmy-Love-Api](https://github.com/EmmyLua/Emmy-love-api) are the way to go in 2023.
