### ISSUE TITLE
11.4 Support

### ISSUE THREAD

**Issue by lawrencematthew19942016** [rm-code/love-IDEA-plugin#17]
Any chance there will be support for the latest version of LOVE? [https://love2d.org/wiki/11.4](url)

**Comment by rm-code** [comment]
Unless the love-api has changed drastically you should be able to update it yourself using the update script:
https://github.com/rm-code/love-IDEA-plugin/blob/master/generator/update.sh

Feel free to submit a PR and I'll happily merge it.
