### ISSUE TITLE
Is it possible to use this in other IDEs from Jetbrains?

### ISSUE THREAD

**Issue by CoalaJoe** [rm-code/love-IDEA-plugin#5]
Title is description.

**Comment by rm-code** [comment]
I don't know, sorry. 

I'd say there is a good chance that you can use this plugin, if the lua-plugin can be installed.

**Comment by CoalaJoe** [comment]
I am currently using PHPStorm and PyCharm. I use the Lua-Plugin but I can't install libraries, seems like that is cust an intelliJ thing, or am I wrong?

**Comment by rm-code** [comment]
> seems like that is cust an intelliJ thing, or am I wrong?

I have only ever used IntelliJ myself so I can't say for sure, but if you have `External Libraries` in the file tree like in IntelliJ I'd say you should be able to install it.

If you find out, I would highly appreciate if you could maybe open a PR with short instructions how to set it up :)

**Comment by CoalaJoe** [comment]
Well. I can add it to the PHP runtime: 
![image](https://cloud.githubusercontent.com/assets/5689499/23842093/33c496ec-07b2-11e7-855e-f93431ed327b.png)

But it does not work.

**Comment by rm-code** [comment]
Ok, instead of installing the whole love-IDEA-plugin repo, try installing one of the subfolders based on the LÖVE version you are using (e.g. `love_0102` for the latest).

**Comment by CoalaJoe** [comment]
Woah. Thanks dude! Missed that one.
I also found the spot in the settings:
![image](https://cloud.githubusercontent.com/assets/5689499/23846251/eab3cb9c-07cc-11e7-97eb-b0179ee3e004.png)

**Comment by rm-code** [comment]
Woooo \o/ So it works now? Then I'll update the README to mention PHPStorm and PyCharm are supported too.

**Comment by CoalaJoe** [comment]
It fully works in PHPStorm.

**Comment by CoalaJoe** [comment]
You can use this images: 
![image](https://cloud.githubusercontent.com/assets/5689499/23850658/a3f72b54-07e0-11e7-8832-6c514d91ba87.png)

I try get PyCharm working aswell.

**Comment by CoalaJoe** [comment]
PyCharm does not seem to have an option to add external libraries. Which makes sense for Python.

**Comment by rm-code** [comment]
Thanks @CoalaJoe, I'll update the README.

**Comment by CoalaJoe** [comment]
Should I try other IDEAs aswell? I have the full palette.

**Comment by rm-code** [comment]
@CoalaJoe If you have the time and want to do it, sure :)

**Comment by CoalaJoe** [comment]
Had no luck with Clion.

**Comment by CoalaJoe** [comment]
- [x] IntelliJ
- [x] PhpStorm
- [ ] ~~AppCode~~
- [ ] ~~DataGrip~~
- [ ] ~~Gogland~~
- [ ] ~~MPS~~
- [ ] ~~Rider~~
- [ ] ~~RubyMine~~
- [x] WebStorm
- [ ] ~~PyCharm~~
- [ ] ~~Clion~~

* Edit: Updated WebStorm @brugnara

**Comment by CoalaJoe** [comment]
It seems like I was lucky and PhpStorm is supported aswell. I didn't get it to work with the other ideas. The only way would be to integrate your helpers into the Lua plugin.

**Comment by rm-code** [comment]
Thank you @CoalaJoe

**Comment by khanhmax** [comment]
sorry I am not the owner of LOVE-IDE-PLUGIN and I am not tried yet. I fork
it from here https://github.com/rm-code/love-IDEA-plugin.

2017-03-15 21:08 GMT+08:00 Robert Machmer <notifications@github.com>:

**Comment by CoalaJoe** [comment]
@khanhmax So you are interessted in porting it to the Lua-Plugin or packaging it as a seperate plugin?

**Comment by brugnara** [comment]
working in webstorm. Just do this:

- open preferences (`CMD` + `,`)
- type "libraries" in the top search box
- open the section "languages" -> "javascript" -> "libraries"
- press `add`
- type a name you want, then leave the rest untuched. Now select the folder as said in the documentation.
- done.

Hope this helps someone.
