### ISSUE TITLE
Debugger for love2d games?

### ISSUE THREAD

**Issue by CoalaJoe** [rm-code/love-IDEA-plugin#6]
I configured my IDEA to debug lua scripts. Does any one know a fix for: 
![image](https://cloud.githubusercontent.com/assets/5689499/23984021/828efac6-0a17-11e7-98f4-f8b40d8ec47e.png)

**Comment by rm-code** [comment]
I've never used the debugger, but it looks like it can't find the love module. Have you tried adding LÖVE to your PATH?

**Comment by CoalaJoe** [comment]
love and lua are in my path.

**Comment by D0NM** [comment]
Set Program: full_path_to_your_love.exe
and in Parameters set the path to your project folder.
