### ISSUE TITLE
Not working on Mac IntelliJ

### ISSUE THREAD

**Issue by hasen6** [rm-code/love-IDEA-plugin#8]
I have the Lua module installed ok and all the code seems to be highlighted but when I type 'love.' there is no autocomplete, only inferred options appear of which there are only a couple. Clearly it's not working despite following your instructions.

I added the love_0102 folder as a Lua Library in Global libraries in project structure. Then applied the changes but still nothing. I have Love 0.10.2 installed as well of course and that works fine. Instructions for Lua and Mac are sparse to say the least but I'm sure there must be a way? It was very hard to get even the Lua module installed and working due to lack of documentation for Mac.

Any ideas what's going wrong here?

**Comment by rm-code** [comment]
I don't have IntelliJ installed on my current system, so I can't test it myself right now. It's possible that something has changed on IntelliJ's or the Lua plugin's end.

> I added the love_0102 folder as a Lua Library in Global libraries in project structure.

Sounds like you've done everything right 😕  It might make sense to ask in the IntelliJ Lua Plugin's repository as well.

**Comment by hasen6** [comment]
Hmm that's unfortunate. Yeah it does seem like I've done everything right I must say. IntelliJ accepted everything too I added in too. Ok thanks for your help anyway.
